# site settings
site-title: Kelina Shrestha
title: Kelina
subtitle: Shrestha
email: kelishrestha97@gmail.com
description: "Self-motivated, dedicated and organized software engineer<br> pursuing professional experience in technology <br>with an aim to solve problems with technology."
baseurl: "/kelina-shrestha" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kelina Shrestha
street_address: Gatthaghar
city: Bhaktapur
state: Bagmati
zip_code: 44600
country: Nepal
phone: (977) 9860790767

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 20

# social settings
500px_url:
facebook_url: https://www.facebook.com/keli.shrestha
github_url: https://github.com/kelishrestha
gitlab_url: https://gitlab.com/kelishrestha
googleplus_url:
instagram_url: https://www.instagram.com/kelishrestha/
linkedin_url: https://www.linkedin.com/in/kelishrestha/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kelishrestha

# experience list
experiences:
  - title: Freelance Remote Software Engineer
    company: KUDO Inc.
    duration: July 2018 - Present
    works:
      - 'Develop rapid application features, stabilize and manage application codes independently.'
      - 'Manage, develop and document API driven applications to provide better flexibility and visibility to team.'
      - 'Manage servers and deployments of the applications.'
      - 'Collaborate remotely with team members across US, Canada and India to efficiently deliver Kanban-sprint hybrid style product life cycle development features.'
      - 'Integrating google based services into platform for better functionality and reporting.'
  - title: Product Manager
    company: BazaarFactory
    duration: July 2017 - Present
    works:
      - 'Create and implement effective solutions to e-commerce platforms’ pain-points.'
      - 'Developed features in early stage of application development.'
      - 'Plan and execute client prioritized features with a vision to support client-first strategy.'
      - 'Lead, coordinate and manage an engineering team for releasing application features and bugs to deliver stable versions of applications.'
      - 'Manage API driven and microservice structured applications with engineering team.'
      - 'Train new engineering team on Rails, GIT, Ruby, Product Development Life Cycle and management facilities.'
      - 'Supervise and manage team from both product and development perspective.'
  - title: Software Engineer
    company: WhiteHat Engineering
    duration: July 2017 - Oct 2017
    works:
      - 'Maintain complete product flow in React based web application.'
      - 'Developed Kanban based product features.'
      - 'Developed email extraction application using GoLang.'
  - title: Associate Software Engineer
    company: CloudFactory (Sprout Technologies)
    duration: July 2016 - July 2017
    works:
      - 'Developed agile microservices and designed multiple APIs with test-driven approach. '
      - 'Managed engineering delivery team with supervision. '
      - 'Integrated tests using testing framework Mocha into the application to test workflow results.'
      - 'Research and prototype building on Central Authentication System (CAS).'
      - 'Developed custom platform service related ruby gems.'
      - 'Contributed in fixing bugs in platform based ruby gem.'
      - 'Remodelled API calls with activemodel concept with multiple microservices.'
      - 'Developed data retention policy in web based applications.'
      - 'Rapid prototyped a short URL API application from discussion to deployment.'
      - 'Support and monitor workflows in platform to address bugs and errors.'
  - title: Junior Software Engineer
    company: CloudFactory (Sprout Technologies)
    duration: June 2015 - July 2016
    works:
      - 'Developed and deliver sprint stories both with peers and independently.'
      - 'Maintain reporting and validation data actively.'
      - 'Fixing and developing platform related bugs and features according to client’s needs.'
      - 'Built custom workflows depending upon requirement of clients.'
      - 'Support and monitor workflows in platform to address bugs and errors at the time of occurence. '
      - 'Worked as a Team Lead of Engineering team collaborating with interdepartmental teams.'
      - 'Managed team and delivered project specific developments cooperating with different innovated teams for fast and quality delivery.'
      - 'Trained subordinates on Rails, GIT and platform overviews.'
      - 'Supervised subordinates on workstreams’ versions to provide several visual and technical benefits to end users.'
      - 'Standardize workflows of available custom workflows by collaborating with workflow development team.'
      - 'Documented complete workflow overview of workflows.'
      - 'Support client’s technical requirements and engaged in client’s  custom workflow technical discussion with both client and interdepartmental teams.'
  - title: Software Engineer Trainee
    company: CloudFactory (Sprout Technologies)
    duration: Jan 2015 - June 2016
    works:
      - 'Actively contributed in development of visualization of reporting features and maintained reporting data in a separate service.'
      - 'Sprint Features development and fixing bugs in platform.'
      - 'Developed new workflow according to client’s requirements.'

# skill lists
skills:
  - category: Programming Languages
    names:
      - Ruby
      - Javascript
      - JQuery
      - HTML
      - CSS
      - Golang(Basic)
      - AJAX
      - VueJS(Basic)
      - ReactJS(Basic)
  - category: Frameworks
    names:
      - Ruby on Rails
      - Sinatra
      - Grape
      - Node
      - ReactJS
      - VueJS
      - Bootstrap
      - Material UI Toolkit
  - category: Database & Web Services
    names:
      - Postgres
      - Redis
      - MongoDB
      - MySQL
      - Redux
      - Amazon S3
  - category: Project Management Tools
    names:
      - HoneyBadger
      - LogEntries
      - Jira
      - Trello
  - category: Software Development Methodology
    names:
      - Agile Methodology with Scrum Process
      - KanBan
      - Rapid Development
  - category: Version Control Tools
    names:
      - Github
      - Gitlab
      - Bitbucket
  - category: Software & Operating Systems
    names:
      - Google Docs, Excels, Presentation
      - Visual Code, Sublime, ATOM
      - MacOS, Linux, Windows
  - category: Personal Skills
    names:
      - Initiative
      - Eager to Learn
      - Working in/as a team
      - Adaptability.
trainings:
  - title: StartUp Weekend Women
    featured_date: 16 February 2018 - 18 February 2018
    image: assets/images/Startup-Glocal-Khabar.jpg
    description: Participated and worked on a Startup Idea as a team for continuous 72 hours.

# education list
education:
  - title: "Bachelor’s in Computer Engineering"
    institution: Khwopa Engineering College
    start_date: 2009
    completion_date: 2015
    major: 'Computer Engineering'
  - title: Intermediate Degree
    institution: Brookfield International College
    start_date: 2007
    completion_date: 2009
    major: 'Science (Biology & Maths)'
  - title: School Leaving Certificate
    institution: BhanuBhakta Higher Secondary School
    start_date: 1999
    completion_date: 2007
    major: 'Computer Science & Maths'


# build settings
markdown: kramdown

sass:
  style: compressed
