# site settings
site-title: Kelina Shrestha
title: Kelina
subtitle: Shrestha
email: kelishrestha97@gmail.com
description: "Self-motivated, dedicated and organized software engineer<br> pursuing professional experience in technology <br>with an aim to solve problems with technology."
baseurl: "/kelina-shrestha" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kelina Shrestha
street_address: Gatthaghar
city: Bhaktapur
state: Bagmati
zip_code: 44600
country: Nepal
phone: (977) 9860790767

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/keli.shrestha
github_url: https://github.com/kelishrestha
gitlab_url: https://gitlab.com/kelishrestha
googleplus_url:
instagram_url: https://www.instagram.com/kelishrestha/
linkedin_url: https://www.linkedin.com/in/kelishrestha/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kelishrestha

# build settings
markdown: kramdown

sass:
  style: compressed
